### ISSUE TITLE
Build freezes

### ISSUE THREAD

**Issue by Akurganow** [webextension-toolbox/webextension-toolbox#292]
Trying to build the extension for chrome

## Expected Behavior
Successful build
## Current Behavior
See this errors:
```
Error: ENOTDIR: not a directory, scandir '/users/user/projects/akurganow/web-ext-clear/create-webpack-config.js'
Error: ENOTDIR: not a directory, scandir '/users/user/projects/akurganow/web-ext-clear/create-webpack-config.js'
    at Object.readdirSync (fs.js:974:3)
    at readDir (/Users/user/Projects/Akurganow/web-ext-clear/node_modules/fork-ts-checker-webpack-plugin/lib/typescript-reporter/file-system/RealFileSystem.js:56:69)
    at Object.readDir (/Users/user/Projects/Akurganow/web-ext-clear/node_modules/fork-ts-checker-webpack-plugin/lib/typescript-reporter/file-system/RealFileSystem.js:145:20)
    at readDir (/Users/user/Projects/Akurganow/web-ext-clear/node_modules/fork-ts-checker-webpack-plugin/lib/typescript-reporter/file-system/PassiveFileSystem.js:53:42)

Compiling

● webpack █████████████████████████ after chunk asset optimization (93%) SourceMapDevToolPlugin scripts/options.js
  generate SourceMap

(node:81896) UnhandledPromiseRejectionWarning: Error: invalid relative path: ../../packages/web-ext-clear.v1.0.0.chrome.zip
    at validateMetadataPath (/Users/user/Projects/Akurganow/web-ext-clear/node_modules/yazl/index.js:368:59)
    at ZipFile.addBuffer (/Users/user/Projects/Akurganow/web-ext-clear/node_modules/yazl/index.js:62:18)
    at /Users/user/Projects/Akurganow/web-ext-clear/node_modules/zip-webpack-plugin/index.js:46:12
    at _next4 (eval at create (/Users/user/Projects/Akurganow/web-ext-clear/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)

Compiling

● webpack █████████████████████████ emitting (95%) ZipPlugin
```
Then build freezes
## Steps to Reproduce (for bugs)
1. Clone [repository](https://github.com/Akurganow/webextension-toolbox-example)
2. Run `npm install`
3. Run `npm run build chrome`

## Your Environment
| Tech | Version |
|-------------------------|---------|
| webextension-toolbox | latest |
| node | v14.4.0 |
| OS | MacOS 10.15.5 |
| browser | Chrome 83.0.4103.106 |

**Comment by tm1000** [comment]
Seems to be working fine now?
