### ISSUE TITLE
Setup with additional webextension-toolbox.config.js config seems to fail on windows 11

### ISSUE THREAD

**Issue by JaroslawPokropinski** [webextension-toolbox/webextension-toolbox#656]
## Expected Behavior
Running dev/build does not throw `Error: Cannot find module` error.

## Current Behavior
Running `webextension-toolbox build -s src --no-manifest-validation "chrome"` throws:
```
Error: Cannot find module 'file:///E:\Programming\Projects\fast-downloader-web-extension\webextension-toolbox.config.js'
Require stack:
- E:\Programming\Projects\fast-downloader-web-extension\node_modules\@webextension-toolbox\webextension-toolbox\dist\common\compile.js
- E:\Programming\Projects\fast-downloader-web-extension\node_modules\@webextension-toolbox\webextension-toolbox\dist\build.js
- E:\Programming\Projects\fast-downloader-web-extension\node_modules\@webextension-toolbox\webextension-toolbox\dist\index.js
- E:\Programming\Projects\fast-downloader-web-extension\node_modules\@webextension-toolbox\webextension-toolbox\dist\command.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:956:15)
    at Function.Module._load (node:internal/modules/cjs/loader:804:27)
    at Module.require (node:internal/modules/cjs/loader:1028:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at E:\Programming\Projects\fast-downloader-web-extension\node_modules\@webextension-toolbox\webextension-toolbox\dist\common\compile.js:41:78
    at async getConfigFile (E:\Programming\Projects\fast-downloader-web-extension\node_modules\@webextension-toolbox\webextension-toolbox\dist\common\compile.js:41:30)
    at async exports.default (E:\Programming\Projects\fast-downloader-web-extension\node_modules\@webextension-toolbox\webextension-toolbox\dist\common\compile.js:53:36)
    at async Command.dev (E:\Programming\Projects\fast-downloader-web-extension\node_modules\@webextension-toolbox\webextension-toolbox\dist\dev.js:12:22) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'E:\\Programming\\Projects\\fast-downloader-web-extension\\node_modules\\@webextension-toolbox\\webextension-toolbox\\dist\\common\\compile.js',
    'E:\\Programming\\Projects\\fast-downloader-web-extension\\node_modules\\@webextension-toolbox\\webextension-toolbox\\dist\\build.js',
    'E:\\Programming\\Projects\\fast-downloader-web-extension\\node_modules\\@webextension-toolbox\\webextension-toolbox\\dist\\index.js',
    'E:\\Programming\\Projects\\fast-downloader-web-extension\\node_modules\\@webextension-toolbox\\webextension-toolbox\\dist\\command.js'
  ]
}
```

## Steps to Reproduce (for bugs)

1. Create `webextension-toolbox.config.js` configuration file
2. Run `npm run dev chrome`

## Context

Running build with additional webpack configuration seems to fail on windows 11.
When i remove
```
if (process.platform === "win32") {
            path = `file:///${path}`;
        }
```
from compile.js it succeeds.

For context I use react, typescript setup and manifest v3 but I don't think that it affects the behavior.

## Your Environment

| Tech                    | Version |
|-------------------------|---------|
| webextension-toolbox    |5.2.2         |
| node                    |v16.17.0         |
| OS                      |Windows 11         |
| browser                 |chrome         |
| etc                     |         |

**Comment by tm1000** [comment]
The reason for the code you removed was so that it worked in github actions on their windows builder.

**Comment by JinKim7** [comment]
for mitigation for other people, you can remove this  portion of highlighted code in your node_modules to be able to build successfully in windows 11

I will try to help and try to submit a PR on trying to fix this issue.

![image](https://user-images.githubusercontent.com/6789394/221341758-5d80b0cc-19e0-475f-978d-3b627ace3953.png)

**Comment by here-nerd** [comment]
> for mitigation for other people, you can remove this portion of highlighted code in your node_modules to be able to build successfully in windows 11
> 
> I will try to help and try to submit a PR on trying to fix this issue.
> 
> ![image](https://user-images.githubusercontent.com/6789394/221341758-5d80b0cc-19e0-475f-978d-3b627ace3953.png)

@JinKim7 is there any update on the issue? 
Is it a good idea to add a CLI configuration for a github actions build vs a windows build?

**Comment by tm1000** [comment]
@here-nerd Whatever works! I'm all for it if we need a work around in github for windows

**Comment by tm1000** [comment]
Resolved in https://github.com/webextension-toolbox/webextension-toolbox/pull/832

**Comment by juharris** [comment]
I'm getting a similar error in with "@webextension-toolbox/webextension-toolbox" version "7.1.1" with Git Bash in Windows.

```shell
$ npx webextension-toolbox dev chrome --config webextension-toolbox.config.js
✔ Loading webpack config from C:\Users\Justin\workspace\onhello\webextension-toolbox.config.js
node:internal/modules/esm/load:239
    throw new ERR_UNSUPPORTED_ESM_URL_SCHEME(parsed, schemes);
          ^

Error [ERR_UNSUPPORTED_ESM_URL_SCHEME]: Only URLs with a scheme in: file, data, and node are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'c:'
    at throwIfUnsupportedURLScheme (node:internal/modules/esm/load:239:11)
    at defaultLoad (node:internal/modules/esm/load:130:3)
    at ModuleLoader.load (node:internal/modules/esm/loader:409:13)
    at ModuleLoader.moduleProvider (node:internal/modules/esm/loader:291:56)
    at new ModuleJob (node:internal/modules/esm/module_job:65:26)
    at #createModuleJob (node:internal/modules/esm/loader:303:17)
    at ModuleLoader.getJobFromResolveResult (node:internal/modules/esm/loader:260:34)
    at ModuleLoader.getModuleJob (node:internal/modules/esm/loader:241:17)
    at async ModuleLoader.import (node:internal/modules/esm/loader:328:23) {
  code: 'ERR_UNSUPPORTED_ESM_URL_SCHEME'
}

Node.js v20.11.1
```

In node_modules\@webextension-toolbox\webextension-toolbox\dist\common\compile.js, I changed:

```JavaScript
const configModule = await import(path);
```
to 
```JavaScript
const configModule = await import(`file://${path}`);
```

and it worked for me.

I tried many ways and combinations to input the path differently for the `--config` argument with a more full path and I don't think it makes a difference.
